# Generated by Django 5.0 on 2024-01-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                choices=[
                    ("CE", "choice1"),
                    ("EXTC", "choice2"),
                    ("ME", "choice3"),
                    ("AI", "choice4"),
                    ("IT", "choice5"),
                ],
                max_length=50,
            ),
        ),
    ]
