# Generated by Django 5.0 on 2024-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                choices=[
                    ("choice1", "CE"),
                    ("choice2", "EXTC"),
                    ("choice3", "ME"),
                    ("choice4", "AI"),
                    ("choice5", "IT"),
                ],
                max_length=50,
            ),
        ),
    ]
