# Generated by Django 5.0 on 2024-01-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_student_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                choices=[
                    ("CE", "CE"),
                    ("EXTC", "EXTC"),
                    ("ME", "ME"),
                    ("AI", "AI"),
                    ("IT", "IT"),
                ],
                max_length=50,
            ),
        ),
    ]
